version: "3"
services: 
    myapp:
        image: app
        depends_on: 
            - mongo
        ports: 
            - "3001:3001"
        networks: 
            - monreseau
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
        networks: 
            - monreseau
networks: 
    monreseau:

#sudo docker-compose up
        




